FROM eclipse-temurin:17 AS app
WORKDIR /app
COPY --from=build:latest /app/target/mindmap.jar /app/target/mindmap.jar
COPY public /app/public
ENTRYPOINT ["java", "-jar", "/app/target/mindmap.jar", "mindmap.Server", "/data"]
