version: '3'
services:
  server:
    image: ghcr.io/michaelmdeng/mindmap/server:latest
    ports:
      - "80:8080"
    volumes:
      - ./data/Dropbox/vimwiki:/data
  grapher:
    image: ghcr.io/michaelmdeng/mindmap/grapher:latest
    volumes:
      - ./data/Dropbox/vimwiki:/data
      - ./generated/graph:/generated
