# Site settings
title: Mindmap
description: 
url: "https://michaelmdeng.com"
author:
  name: "Michael Deng"
  email: "michaelmdeng@gmail.com"
  url: "michaelmdeng@gmail.cm"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
permalink: /:title/
disable_disk_cache: true

sass:
    sass_dir: _sass
    style: compact

# Default values
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      render_with_liquid: false

# Plugins
plugins:
  - jekyll-optional-front-matter

optional_front_matter:
  remove_originals: true
